### ISSUE TITLE
add sorting, grouping, filtering defaults?

### ISSUE THREAD

**Issue by jeremyp** [smcmahon/collective.jqxgrid_pages#3]
Would it be possible to allow for sorting, grouping, and filtering defaults?

For sorting, the use case would be to specify one (or more) of the display columns as the default for sorting. E.g., if I have a course listing with a "course number" field, I could specify that as the default field to sort by so that the initial presentation of the grid showed ascending course numbers.

For grouping, the use case would be to specify one of the display columns as the grouping default. E.g., if I have a listing of individual sections of courses where the "course number" field is duplicated on each row, I could specify that the default presentation of the grid would group by the course number so that the user could expand the course number row to see all sections for that course.

For filtering, the use case would be to specify a default filter for one or more columns. E.g., if I have a listing of courses with an "instructor name" field, I could designate that field as the default filter and provide a filter string to limit the initial display to courses offered by instructors whose last names are "Smith".

**Comment by smcmahon** [comment]
Sorting and grouping done; in latest commit.

**Comment by smcmahon** [comment]
Simple filtering added.
